# -*- coding: utf-8 -*-
"""final_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UoNDcNziPO0UcRMQi1TRfPoI9ymKScPc

# Roshane Shahbaz - 220444
"""

# -*- coding: utf-8 -*-
"""final.py - Demo Version with Synthetic Data
Works without actual CSV file
Generates .pkl files using save_processed_data
"""

import pandas as pd
from collections import Counter, defaultdict
import math
import os
import pickle
import re


# PART A: DATA PREPROCESSING

def load_data(filepath=None):
    """Load Twitter data from CSV file or generate synthetic data."""
    if filepath and os.path.exists(filepath):
        df = pd.read_csv(filepath, encoding='latin-1', header=None,
                         names=['target', 'ids', 'date', 'flag', 'user', 'text'],
                         on_bad_lines='skip', engine='python', nrows=50000)
        return df['text'].tolist()
    else:
        # Synthetic data for demo
        print("⚠ CSV not found. Using synthetic data for demo...")
        synthetic_tweets = [
            "i love this song",
            "how are you today",
            "the weather is nice",
            "good morning everyone",
            "i am feeling great",
            "python is awesome",
            "machine learning rocks",
            "artificial intelligence is cool",
            "i hate monday mornings",
            "you are amazing",
        ] * 5000  # 50k tweets
        return synthetic_tweets


def tokenize_sentences(sentences):
    """Tokenize sentences and convert to lowercase."""
    tokenized = []
    for sent in sentences:
        words = re.findall(r'\b\w+\b|[.!?]', sent.lower())
        tokenized.append(words)
    return tokenized


def train_test_split(sentences, test_ratio=0.2):
    """Split into train and test sets."""
    split_idx = int(len(sentences) * (1 - test_ratio))
    return sentences[:split_idx], sentences[split_idx:]


def get_word_counts(train_data):
    """Count word frequencies in training data."""
    counts = Counter()
    for sent in train_data:
        counts.update(sent)
    return counts


def get_closed_vocabulary(word_counts, threshold=5):
    """Get vocabulary with words appearing >= threshold times."""
    return {word for word, count in word_counts.items() if count >= threshold}


def replace_oov(sentences, vocab, unk_token='<unk>'):
    """Replace out-of-vocabulary words with unknown token."""
    return [[w if w in vocab else unk_token for w in sent] for sent in sentences]


def preprocess(filepath=None, threshold=5, test_ratio=0.2):
    """Complete preprocessing pipeline."""
    print(f"Loading data...")
    data = load_data(filepath)
    print(f"✓ Loaded {len(data):,} tweets")

    print("Tokenizing sentences...")
    tokenized = tokenize_sentences(data)

    print("Splitting train/test sets...")
    train, test = train_test_split(tokenized, test_ratio)

    print("Building vocabulary...")
    word_counts = get_word_counts(train)
    vocab = get_closed_vocabulary(word_counts, threshold)

    print("Replacing OOV words...")
    train = replace_oov(train, vocab)
    test = replace_oov(test, vocab)

    return train, test, vocab


# PART B: N-GRAM LANGUAGE MODELS

def count_ngrams(sentences, n, start_token='<s>', end_token='<e>'):
    """Count n-grams from sentences."""
    counts = defaultdict(int)

    for sent in sentences:
        padded = [start_token] * (n - 1) + sent + [end_token]

        for i in range(len(padded) - n + 1):
            counts[tuple(padded[i:i+n])] += 1

    return dict(counts)


def estimate_probability(word, prev_ngram, ngram_counts, prev_ngram_counts, vocab_size, k=1.0):
    """Estimate probability with k-smoothing."""
    full_ngram = prev_ngram + (word,)
    numerator = ngram_counts.get(full_ngram, 0) + k
    denominator = prev_ngram_counts.get(prev_ngram, 0) + k * vocab_size
    return numerator / denominator if denominator > 0 else 0


def estimate_all_probabilities(prev_ngram, vocabulary, ngram_counts, prev_ngram_counts, vocab_size, k=1.0):
    """Estimate probabilities for all words."""
    probs = {}
    for word in vocabulary:
        probs[word] = estimate_probability(word, prev_ngram, ngram_counts, prev_ngram_counts, vocab_size, k)
    return probs


def make_count_matrix(ngram_counts, vocabulary, n):
    """Create count matrix for n-grams."""
    matrix = {}
    for ngram, count in ngram_counts.items():
        if len(ngram) == n:
            prev = ngram[:-1]
            if prev not in matrix:
                matrix[prev] = {}
            matrix[prev][ngram[-1]] = count
    return matrix


def make_probability_matrix(ngram_counts, prev_ngram_counts, vocabulary, k=1.0):
    """Create probability matrix for n-grams."""
    vocab_size = len(vocabulary)
    matrix = {}

    for prev_ngram in prev_ngram_counts.keys():
        matrix[prev_ngram] = estimate_all_probabilities(
            prev_ngram, vocabulary, ngram_counts, prev_ngram_counts, vocab_size, k
        )

    return matrix


# PART C: PERPLEXITY EVALUATION

def calculate_perplexity(sentences, ngram_counts, prev_ngram_counts, vocabulary, n, k=1.0):
    """Calculate perplexity score."""
    vocab_size = len(vocabulary)
    total_log_prob = 0.0
    total_words = 0

    for sent in sentences:
        padded = ['<s>'] * (n - 1) + sent + ['<e>']

        for i in range(n - 1, len(padded)):
            prev_ngram = tuple(padded[i-n+1:i])
            word = padded[i]

            full_ngram = prev_ngram + (word,)
            numerator = ngram_counts.get(full_ngram, 0) + k
            denominator = prev_ngram_counts.get(prev_ngram, 0) + k * vocab_size

            prob = numerator / denominator if denominator > 0 else k / (k * vocab_size)
            total_log_prob += math.log(prob)
            total_words += 1

    if total_words == 0:
        return float('inf')

    return math.exp(-total_log_prob / total_words)


# PART D: AUTO-COMPLETE SYSTEM

def get_suggestions(sentence, ngram_models, vocabulary, k=1.0, start_with=None, top_k=5):
    """Get word suggestions from n-gram models."""
    tokens = [w.lower() for w in re.findall(r'\b\w+\b|[.!?]', sentence.lower())]
    all_suggestions = {}

    for n in sorted(ngram_models.keys()):
        ngram_counts, prev_ngram_counts = ngram_models[n]

        prev_ngram = tuple(tokens[-(n-1):]) if len(tokens) >= n-1 else tuple(['<s>'] * (n-1-len(tokens)) + tokens)

        for word in vocabulary:
            if start_with and not word.startswith(start_with):
                continue

            full_ngram = prev_ngram + (word,)
            numerator = ngram_counts.get(full_ngram, 0) + k
            denominator = prev_ngram_counts.get(prev_ngram, 0) + k * len(vocabulary)
            prob = numerator / denominator if denominator > 0 else k / (k * len(vocabulary))

            if word not in all_suggestions:
                all_suggestions[word] = prob
            else:
                all_suggestions[word] = max(all_suggestions[word], prob)

    ranked = sorted(all_suggestions.items(), key=lambda x: x[1], reverse=True)
    return [w for w, _ in ranked[:top_k]]


def save_project_outputs(train_data, test_data, vocabulary, ngram_models, perplexity_results, autocomplete_samples):
    """Save all outputs to .pkl and .txt files"""

    # Create directories
    os.makedirs('data/processed', exist_ok=True)
    os.makedirs('results', exist_ok=True)

    print("\n" + "="*60)
    print("SAVING PROJECT OUTPUTS")
    print("="*60)

    # Save pickle files
    with open('data/processed/train_data.pkl', 'wb') as f:
        pickle.dump(train_data, f)
    print(f"✓ Saved: data/processed/train_data.pkl ({len(train_data):,} sentences)")

    with open('data/processed/test_data.pkl', 'wb') as f:
        pickle.dump(test_data, f)
    print(f"✓ Saved: data/processed/test_data.pkl ({len(test_data):,} sentences)")

    with open('data/processed/vocabulary.pkl', 'wb') as f:
        pickle.dump(vocabulary, f)
    print(f"✓ Saved: data/processed/vocabulary.pkl ({len(vocabulary):,} words)")

    with open('data/processed/ngram_models.pkl', 'wb') as f:
        pickle.dump(ngram_models, f)
    print(f"✓ Saved: data/processed/ngram_models.pkl (1-6 grams)")

    # Save text results
    with open('results/perplexity_results.txt', 'w') as f:
        f.write("PERPLEXITY SCORES\n" + "="*40 + "\n\n")
        for n, score in sorted(perplexity_results.items()):
            f.write(f"{n}-gram: {score:.4f}\n")
    print(f"✓ Saved: results/perplexity_results.txt")

    with open('results/autocomplete_samples.txt', 'w') as f:
        f.write("AUTOCOMPLETE EXAMPLES\n" + "="*40 + "\n\n")
        for input_text, suggestions in autocomplete_samples:
            f.write(f"Input: '{input_text}'\n")
            f.write(f"Suggestions: {suggestions}\n\n")
    print(f"✓ Saved: results/autocomplete_samples.txt")

    # Summary report
    with open('results/processing_summary.txt', 'w') as f:
        f.write(f"""NLP AUTOCOMPLETE PROJECT - PROCESSING SUMMARY
{'='*50}

DATA STATISTICS:
  Training sentences: {len(train_data):,}
  Test sentences: {len(test_data):,}
  Vocabulary size: {len(vocabulary):,}

N-GRAM MODELS:
  Models built: 1-gram to 6-gram

PERPLEXITY SCORES:
""")
        for n, score in sorted(perplexity_results.items()):
            f.write(f"  {n}-gram: {score:.4f}\n")

        f.write(f"""
AUTOCOMPLETE SAMPLES: {len(autocomplete_samples)} tested

OUTPUT FILES:
  ✓ data/processed/train_data.pkl
  ✓ data/processed/test_data.pkl
  ✓ data/processed/vocabulary.pkl
  ✓ data/processed/ngram_models.pkl
  ✓ results/perplexity_results.txt
  ✓ results/autocomplete_samples.txt
""")
    print(f"✓ Saved: results/processing_summary.txt")

    print("="*60)
    print("✓ ALL OUTPUTS SAVED")
    print("="*60)


def main(data_path=None, threshold=5, test_ratio=0.2):
    """Execute complete pipeline."""

    print("\n" + "="*60)
    print("NLP AUTO-COMPLETE SYSTEM")
    print("="*60)

    print("\n[PART A] Preprocessing Data...")
    train_data, test_data, vocabulary = preprocess(data_path, threshold, test_ratio)
    print(f"✓ Train: {len(train_data):,}, Test: {len(test_data):,}, Vocab: {len(vocabulary):,}")

    print("\n[PART B] Building N-gram Models...")
    ngram_models = {}
    perplexity_results = {}

    for n in range(1, 7):
        ngram_counts = count_ngrams(train_data, n)
        prev_counts = defaultdict(int)
        for ngram in ngram_counts:
            prev_counts[ngram[:-1]] += ngram_counts[ngram]
        ngram_models[n] = (ngram_counts, dict(prev_counts))
        print(f"  {n}-gram: {len(ngram_counts):,} unique n-grams")

    print("\n[PART C] Evaluating Models...")
    for n in range(1, 7):
        ngram_counts, prev_counts = ngram_models[n]
        perp = calculate_perplexity(test_data, ngram_counts, prev_counts, vocabulary, n)
        perplexity_results[n] = perp
        print(f"  {n}-gram perplexity: {perp:.4f}")

    print("\n[PART D] Auto-Complete System...")
    test_sentences = ["i love", "how are you", "the weather", "good morning", "i am"]
    autocomplete_samples = []

    for sent in test_sentences:
        sugg = get_suggestions(sent, ngram_models, vocabulary, top_k=5)
        print(f"  '{sent}' → {sugg}")
        autocomplete_samples.append((sent, sugg))

    # SAVE ALL OUTPUTS
    save_project_outputs(train_data, test_data, vocabulary, ngram_models,
                        perplexity_results, autocomplete_samples)

    print("\nComplete!")

    return train_data, test_data, vocabulary, ngram_models


if __name__ == "__main__":
    train_data, test_data, vocabulary, ngram_models = main()